// Máquinas fictícias usadas como PLACEHOLDER visual.
// Só aparecem quando a API real não retorna anúncios (ex.: ambiente de preview
// sem backend). Em produção, os dados reais da API sempre têm prioridade.
const img = (n) => `/img/maq-${n}.jpg`

export const MOCK_LISTINGS = [
  {
    id: 'demo-1',
    title: 'Mini escavadeira YANMAR ViO17',
    category: 'mini_escavadeira',
    model: 'ViO17',
    year: 2022,
    hours_used: 320,
    price: 148000,
    cover_url: img(1),
    dealer_name: 'AgroSul Máquinas',
    city: 'Campinas',
    state: 'SP',
  },
  {
    id: 'demo-2',
    title: 'Mini pá carregadeira YANMAR V8',
    category: 'mini_pa_carregadeira',
    model: 'V8',
    year: 2021,
    hours_used: 1100,
    price: 132000,
    cover_url: img(2),
    dealer_name: 'Constru Tech SP',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 'demo-3',
    title: 'Mini retroescavadeira YANMAR CBL40',
    category: 'mini_retroescavadeira',
    model: 'CBL40',
    year: 2019,
    hours_used: 2400,
    price: 98000,
    cover_url: img(3),
    dealer_name: 'Máquinas Ribeirão',
    city: 'Ribeirão Preto',
    state: 'SP',
  },
  {
    id: 'demo-4',
    title: 'Mini escavadeira YANMAR ViO55',
    category: 'mini_escavadeira',
    model: 'ViO55',
    year: 2023,
    hours_used: 180,
    price: 210000,
    cover_url: img(4),
    dealer_name: 'Constru Paraná',
    city: 'Curitiba',
    state: 'PR',
  },
  {
    id: 'demo-5',
    title: 'Mini pá carregadeira YANMAR V4',
    category: 'mini_pa_carregadeira',
    model: 'V4',
    year: 2020,
    hours_used: 950,
    price: 89000,
    cover_url: img(5),
    dealer_name: 'Energia Sul RS',
    city: 'Porto Alegre',
    state: 'RS',
  },
  {
    id: 'demo-6',
    title: 'Mini escavadeira YANMAR ViO35',
    category: 'mini_escavadeira',
    model: 'ViO35',
    year: 2021,
    hours_used: 640,
    price: 165000,
    cover_url: img(6),
    dealer_name: 'YANMAR Agro Goiás',
    city: 'Goiânia',
    state: 'GO',
  },
]
